blank_issues_enabled: true
contact_links:
  - name: Stackoverflow
    url: https://stackoverflow.com/questions/ask?tags=python-fixtup
    about: Please ask and answer questions about fixtup usage here
